a = input('Digite algo:')
print('O tipo primitivo é',type (a))
print('Só tem espaços?',a.isspace())
print('É um número?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfabético e númerico?',a.isalnum())
print('É maiúsculos?',a.isupper())
print('É minúsculos?',a.islower())
print('Esta com a primeira letra maiúscula?',a.istitle())